name: wheat
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.12.0
  geolocator: ^14.0.2
  carousel_slider: ^5.1.1
  model_viewer_plus: ^1.10.0
  shared_preferences: ^2.2.2
  intl: ^0.19.0
  dio: ^5.9.0
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/Data/day1/images/
    - assets/Data/day2/images/
    - assets/Data/day3/images/
    - assets/Data/day4/images/
    - assets/Data/day5/images/
    - assets/Data/day6/images/
    - assets/Data/day7/images/
    - assets/Data/day8/images/
    - assets/Data/day9/images/
    - assets/Data/day10/images/
    - assets/Data/day11/images/
    - assets/Data/day12/images/
    - assets/Data/day13/images/
    - assets/Data/day14/images/
    - assets/Data/day15/images/
    - assets/Data/day16/images/
    - assets/Data/day17/images/
    - assets/Data/day18/images/
    - assets/Data/day19/images/
    - assets/Data/day20/images/
    - assets/Data/day21/images/
    - assets/Data/day22/images/
    - assets/Data/day23/images/
    - assets/Data/day24/images/
    - assets/Data/day25/images/
    - assets/Data/day26/images/
    - assets/Data/day27/images/
    - assets/Data/day28/images/
    - assets/Data/day29/images/
    - assets/Data/day30/images/
    - assets/Data/day31/images/
    - assets/Data/day32/images/
    - assets/Data/day33/images/
    - assets/Data/day34/images/
    - assets/Data/day35/images/
    - assets/Data/day36/images/
    - assets/Data/day37/images/
    - assets/Data/day38/images/
    - assets/Data/day39/images/
    - assets/Data/day40/images/
    - assets/Data/day41/images/
    - assets/Data/day42/images/
    - assets/Data/day43/images/
    - assets/Data/day44/images/
    - assets/Data/day45/images/
    - assets/Data/day46/images/
    - assets/Data/day47/images/
    - assets/Data/day48/images/
    - assets/Data/day49/images/
    - assets/Data/day50/images/
    - assets/Data/day51/images/
    - assets/Data/day52/images/
    - assets/Data/day53/images/
    - assets/Data/day54/images/
    - assets/Data/day55/images/
    - assets/Data/day56/images/
    - assets/Data/day57/images/
    - assets/Data/day58/images/
    - assets/Data/day59/images/
    - assets/Data/day60/images/
    - assets/Data/day61/images/
    - assets/Data/day62/images/
    - assets/Data/day63/images/
    - assets/Data/day64/images/
    - assets/Data/day65/images/
    - assets/Data/day66/images/
    - assets/Data/day67/images/
    - assets/Data/day68/images/
    - assets/Data/day69/images/
    - assets/Data/day70/images/
    - assets/Data/day71/images/
    - assets/Data/day72/images/
    - assets/Data/day73/images/
    - assets/Data/day74/images/
    - assets/Data/day75/images/
    - assets/Data/day76/images/
    - assets/Data/day77/images/
    - assets/Data/day78/images/
    - assets/Data/day79/images/
    - assets/Data/day80/images/
    - assets/Data/day81/images/
    - assets/Data/day82/images/
    - assets/Data/day83/images/
    - assets/Data/day84/images/
    - assets/Data/day85/images/
    - assets/Data/day86/images/
    - assets/Data/day87/images/
    - assets/Data/day88/images/
    - assets/Data/day89/images/
    - assets/Data/day90/images/
    - assets/Data/day91/images/
    - assets/Data/day92/images/
    - assets/Data/day93/images/
    - assets/Data/day94/images/
    - assets/Data/day95/images/
    - assets/Data/day96/images/
    - assets/Data/day97/images/
    - assets/Data/day98/images/
    - assets/Data/day99/images/
    - assets/Data/day100/images/
    - assets/requirements/
    - assets/onboarding/
    - assets/extracted_frames_comp/6th jan/1/
    - assets/extracted_frames_comp/7th jan/1/
    - assets/extracted_frames_comp/8th jan/1/
    - assets/extracted_frames_comp/9th jan/1/
    - assets/extracted_frames_comp/10th jan/1/
    - assets/extracted_frames_comp/11th jan/1/
    - assets/extracted_frames_comp/12th jan/1/
    - assets/extracted_frames_comp/13th jan/1/
    - assets/extracted_frames_comp/14th jan/1/
    - assets/extracted_frames_comp/15th jan/1/
    - assets/extracted_frames_comp/16th jan/1/
    - assets/extracted_frames_comp/17th jan/1/
    - assets/extracted_frames_comp/18th jan/1/
    - assets/extracted_frames_comp/19th jan/1/
    - assets/extracted_frames_comp/20th jan/1/
    - assets/extracted_frames_comp/21th jan/1/
