name: first_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.9.2

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  geolocator: ^14.0.2
  shared_preferences: ^2.5.3
  intl: ^0.20.2
  path_provider: ^2.1.5
  carousel_slider: ^5.1.1
  model_viewer_plus: ^1.7.0
  flutter_3d_controller: ^2.3.0
dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  assets:
    - assets1/models1/
    - assets/images/image.png
    - assets/Models/
    - assets/Data/
    - assets/Data/day1/day1.txt
    - assets/Data/day1/images/
    - assets/Data/day2/day2.txt
    - assets/Data/day2/images/
    - assets/Data/day3/day3.txt
    - assets/Data/day3/images/
    - assets/Data/day4/day4.txt
    - assets/Data/day4/images/
    - assets/Data/day5/day5.txt
    - assets/Data/day5/images/
    - assets/Data/day6/day6.txt
    - assets/Data/day6/images/
    - assets/Data/day7/day7.txt
    - assets/Data/day7/images/
    - assets/Data/day8/day8.txt
    - assets/Data/day8/images/
    - assets/Data/day9/day9.txt
    - assets/Data/day9/images/
    - assets/Data/day10/day10.txt
    - assets/Data/day10/images/
    - assets/Data/day11/day11.txt
    - assets/Data/day11/images/
    - assets/Data/day12/day12.txt
    - assets/Data/day12/images/
    - assets/Data/day13/day13.txt
    - assets/Data/day13/images/
    - assets/Data/day14/day14.txt
    - assets/Data/day14/images/
    - assets/Data/day15/day15.txt
    - assets/Data/day15/images/
    - assets/Data/day16/day16.txt
    - assets/Data/day16/images/
    - assets/Data/day17/day17.txt
    - assets/Data/day17/images/
    - assets/Data/day18/day18.txt
    - assets/Data/day18/images/
    - assets/Data/day19/day19.txt
    - assets/Data/day19/images/
    - assets/Data/day20/day20.txt
    - assets/Data/day20/images/
    - assets/Data/day21/day21.txt
    - assets/Data/day21/images/
    - assets/Data/day22/day22.txt
    - assets/Data/day22/images/
    - assets/Data/day23/day23.txt
    - assets/Data/day23/images/
    - assets/Data/day24/day24.txt
    - assets/Data/day24/images/
    - assets/Data/day25/day25.txt
    - assets/Data/day25/images/
    - assets/Data/day26/day26.txt
    - assets/Data/day26/images/
    - assets/Data/day27/day27.txt
    - assets/Data/day27/images/
    - assets/Data/day28/day28.txt
    - assets/Data/day28/images/
    - assets/Data/day29/day29.txt
    - assets/Data/day29/images/
    - assets/Data/day30/day30.txt
    - assets/Data/day30/images/
    - assets/Data/day31/day31.txt
    - assets/Data/day31/images/
    - assets/Data/day32/day32.txt
    - assets/Data/day32/images/
    - assets/Data/day33/day33.txt
    - assets/Data/day33/images/
    - assets/Data/day34/day34.txt
    - assets/Data/day34/images/
    - assets/Data/day35/day35.txt
    - assets/Data/day35/images/
    - assets/Data/day36/day36.txt
    - assets/Data/day36/images/
    - assets/Data/day37/day37.txt
    - assets/Data/day37/images/
    - assets/Data/day38/day38.txt
    - assets/Data/day38/images/
    - assets/Data/day39/day39.txt
    - assets/Data/day39/images/
    - assets/Data/day40/day40.txt
    - assets/Data/day40/images/
    - assets/Data/day41/day41.txt
    - assets/Data/day41/images/
    - assets/Data/day42/day42.txt
    - assets/Data/day42/images/
    - assets/Data/day43/day43.txt
    - assets/Data/day43/images/
    - assets/Data/day44/day44.txt
    - assets/Data/day44/images/
    - assets/Data/day45/day45.txt
    - assets/Data/day45/images/
    - assets/Data/day46/day46.txt
    - assets/Data/day46/images/
    - assets/Data/day47/day47.txt
    - assets/Data/day47/images/
    - assets/Data/day48/day48.txt
    - assets/Data/day48/images/
    - assets/Data/day49/day49.txt
    - assets/Data/day49/images/
    - assets/Data/day50/day50.txt
    - assets/Data/day50/images/
    - assets/Data/day51/day51.txt
    - assets/Data/day51/images/
    - assets/Data/day52/day52.txt
    - assets/Data/day52/images/
    - assets/Data/day53/day53.txt
    - assets/Data/day53/images/
    - assets/Data/day54/day54.txt
    - assets/Data/day54/images/
    - assets/Data/day55/day55.txt
    - assets/Data/day55/images/
    - assets/Data/day56/day56.txt
    - assets/Data/day56/images/
    - assets/Data/day57/day57.txt
    - assets/Data/day57/images/
    - assets/Data/day58/day58.txt
    - assets/Data/day58/images/
    - assets/Data/day59/day59.txt
    - assets/Data/day59/images/
    - assets/Data/day60/day60.txt
    - assets/Data/day60/images/
    - assets/Data/day61/day61.txt
    - assets/Data/day61/images/
    - assets/Data/day62/day62.txt
    - assets/Data/day62/images/
    - assets/Data/day63/day63.txt
    - assets/Data/day63/images/
    - assets/Data/day64/day64.txt
    - assets/Data/day64/images/
    - assets/Data/day65/day65.txt
    - assets/Data/day65/images/
    - assets/Data/day66/day66.txt
    - assets/Data/day66/images/
    - assets/Data/day67/day67.txt
    - assets/Data/day67/images/
    - assets/Data/day68/day68.txt
    - assets/Data/day68/images/
    - assets/Data/day69/day69.txt
    - assets/Data/day69/images/
    - assets/Data/day70/day70.txt
    - assets/Data/day70/images/
    - assets/Data/day71/day71.txt
    - assets/Data/day71/images/
    - assets/Data/day72/day72.txt
    - assets/Data/day72/images/
    - assets/Data/day73/day73.txt
    - assets/Data/day73/images/
    - assets/Data/day74/day74.txt
    - assets/Data/day74/images/
    - assets/Data/day75/day75.txt
    - assets/Data/day75/images/
    - assets/Data/day76/day76.txt
    - assets/Data/day76/images/
    - assets/Data/day77/day77.txt
    - assets/Data/day77/images/
    - assets/Data/day78/day78.txt
    - assets/Data/day78/images/
    - assets/Data/day79/day79.txt
    - assets/Data/day79/images/
    - assets/Data/day80/day80.txt
    - assets/Data/day80/images/
    - assets/Data/day81/day81.txt
    - assets/Data/day81/images/
    - assets/Data/day82/day82.txt
    - assets/Data/day82/images/
    - assets/Data/day83/day83.txt
    - assets/Data/day83/images/
    - assets/Data/day84/day84.txt
    - assets/Data/day84/images/
    - assets/Data/day85/day85.txt
    - assets/Data/day85/images/
    - assets/Data/day86/day86.txt
    - assets/Data/day86/images/
    - assets/Data/day87/day87.txt
    - assets/Data/day87/images/
    - assets/Data/day88/day88.txt
    - assets/Data/day88/images/
    - assets/Data/day89/day89.txt
    - assets/Data/day89/images/
    - assets/Data/day90/day90.txt
    - assets/Data/day90/images/
    - assets/Data/day91/day91.txt
    - assets/Data/day91/images/
    - assets/Data/day92/day92.txt
    - assets/Data/day92/images/
    - assets/Data/day93/day93.txt
    - assets/Data/day93/images/
    - assets/Data/day94/day94.txt
    - assets/Data/day94/images/
    - assets/Data/day95/day95.txt
    - assets/Data/day95/images/
    - assets/Data/day96/day96.txt
    - assets/Data/day96/images/
    - assets/Data/day97/day97.txt
    - assets/Data/day97/images/
    - assets/Data/day98/day98.txt
    - assets/Data/day98/images/
    - assets/Data/day99/day99.txt
    - assets/Data/day99/images/
    - assets/Data/day100/day100.txt
    - assets/Data/day100/images/


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
